#!/usr/bin/env bash
# Configure Nginx server
# configure error actions

# to Upadate the Packages
sudo apt-get update
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# doing redirection (301)
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/ISSAM-SLI permanent;"

sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# customized 404 error
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default
# customized HTTP header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
# Restarting Nginx
sudo nginx -t
sudo service nginx restart
