#!usr/bin/env bash
# install ufw firewell and setup a few rules on web-01

sudo apt update
sudo apt install ufw

ufw default deny incoming
ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
sudo ufw status verbose
